version: '3'

services:

  nats-server:
    image: nats:latest
    ports:
      #- 4222:4222 //no exponemos este puerto porque ya lo usa la aplicacion en la red interna de docker
      - 8222:8222
      #- 6222-6222

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GASTEWAY_PORT_EXPOSE}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
  
  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
      
  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDOPOINT_SECRET=${STRIPE_ENDOPOINT_SECRET}
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}